@startuml

class Monitor <<aggregate>>{
    - Id: int
    - Guid : Guid
    - Name: string
    - Hosts : IReadOnlyCollection<Host>
    + Monitor(string name)
    + AddHost(Host host)
    + RemoveHost(Host host)
    + CurrentQuantity()
}

class Host <<aggregate>>{
    -Id: int
    -Hostname: string
    -Alias: string?
    -IPAdress: string
    -Description: Description
    -ServicesInUse: IReadOnlyCollection<Service>
    +Host(string hostname, string ipadress, Description description)
    +AddService(Service service)
    +RemoveService(Service service)
    +SetAlias(string alias)
    +SetIP(string ip)
    +SetHostname(string hostname)
    +SetDescription(string desc)
}
class Service<<aggregate>>{
    -Id: int
    -Host: Host
    -NormalInterval: int
    -RetryInterval: int
    -Description: Description
    -ProducedWarnings: IReadOnlyCollection<Warning>
    +Service(Host host, int ninterval, int rinterval, Description description)
    +SetNormalInterval(int n)
    +SetRetryInterval(int r)
    +SetDescription(string desc)
    +CreateWarning()
    +ReviewWarning(Warning warning, bool fixed, string notes)
    +CalculateAveragePriority()
    +GetLastWarning()

}

class CustomService{
    -Command: string
    -ServiceType: string/Discriminator/
    +CustomService(string command)
}

class Description <<value object>>{
    -Description: string
    -DescriptionLong: string?
}

class Warning{
    -Id: int
    -Host: Host
    -Service: Service
    -Description: Description
    -Priority: int
    -Date: DateTime
    +Warning(Host host, Service Service, int priority, DateTime date, Description description)
    +SetDescription(string desc)
    +SetPriority(int priority)
}

class ReviewedWarning{
    -Fixed: bool?
    -Notes: string
    -WarningType: string/Discriminator/
    +ReviewWarning(Warning warning, bool fixed, string notes)
}

class DeviceType <<aggregate>>{
    -Id: int
    -Type: string
    -OperatingSystem: string?
    +DeviceType(string type)
    +SetOS(string os)
}

ReviewedWarning -up-|> Warning
CustomService -up-|> Service
Host *--> Description
Service *--> Description
Warning *--> Description
Host <--> Service
Monitor o--> Host
DeviceType o--> Host
Service <--> Warning


@enduml