@startuml

class Monitor <<aggregate>>{
    - Id: int
    - Guid : Guid
    - Name: string
    - Hosts : IReadOnlyCollection<Host>
    + Monitor(string name)
    + AddHost(Host host)
    + RemoveHost(Host host)
    + CurrentQuantity()
}
class Message{
    -Id: int
    -Host: Host
    -Service: Service
    -Description: Description
    -Date: DateTime
    +Message(Host host, Service service, Description description)
}
class Host <<aggregate>>{
    -Id: int
    -Hostname: string
    -Alias: string?
    -IPAdress: string
    -Description: Description
    -ServicesInUse: IReadOnlyCollection<Service>
    +Host(string hostname, string ipadress, Description description)
    +AddService(Service service)
    +CurrentServiceQuantity()
    +RemoveService(Service service)
    +SetAlias(string alias)
    +SetIP(string ip)
    +SetHostname(string hostname)
    +SetDescription(Description desc)
}
class Service<<aggregate>>{
    -Id: int
    -Host: Host
    -NormalInterval: int
    -RetryInterval: int
    -Description: Description
    -ProducedWarnings: IReadOnlyCollection<Warning>
    -ReviewedWarnings: IReadOnlyCollection<ReviewedWarning>
    +Service(Host host, int ninterval, int rinterval, Description description)
    +SetNormalInterval(int n)
    +SetRetryInterval(int r)
    +SetDescription(Description desc)
    +CreateWarning(Host host, Service service, int priority, Description description)
    +ReviewWarning(Warning warning, bool fixed, string notes)
    +CalculateAveragePriority()
    +GetLastWarning()
    +GetLastReviewedWarning()

}

class CustomService{
    -Command: string
    -ServiceType: string/Discriminator/
    +CustomService(string command)
}

class PlugIn{
    -Id: int
    -Name: string
    -URL: string
    -ServiceType: string/Discriminator/
    +Plugin(string name, string url)
}

class Description <<value object>>{
    -Description: string
    -DescriptionLong: string?
}

class Warning{
    -Id: int
    -Host: Host
    -Service: Service
    -Description: Description
    -Priority: int
    -Date: DateTime
    +Warning(Host host, Service service, int priority, Description description)
    +SetDescription(Description desc)
    +SetPriority(int priority)
    
}

class ReviewedWarning{
    -Fixed: bool?
    -Notes: string
    -WarningType: string/Discriminator/
    +ReviewWarning(Warning warning, bool fixed, string notes)
}



ReviewedWarning -up-|> Warning
CustomService -up-|> Service
PlugIn -up-|> Service
Host *--> Description
Service *--> Description
Warning *--> Description
Message *--> Description
Host <--> Service
Monitor o--> Host
Service <--> Warning
Service <--> Message

@enduml